### PR TITLE
docs: update documentation for more streamlined website

### PR DESCRIPTION
**Pull request by younesStrittmatter**
The purpose of this is to generate a more streamlined website look.
- Make naming conventions more explicit
- index page as front page for the package 
- quickstart guide in each package
- jupiter notebook examples as subsections

### CODE REVIEW

**Review by musslick — APPROVED** [review]
Looks great!

**Comment by benwandrew** [comment]
just curious about why some file names use an underscore between words and some use a dash? eg, `test_experimentalist_pooler_example.py` in `tests` vs `quick-start.md` or `basic-usage.ipynb` in `docs`

**Comment by younesStrittmatter** [comment]
I am not sure either, but the convention I use: everything python ends has underscores (as in the imports), everything websites hase dashes (like in most urls).

**Comment by younesStrittmatter** [comment]
so basicaly: if something ends with .py it should use underscores, if it ends with .md or ipynb it should use dashes

**Comment by benwandrew** [comment]
gotcha, that makes sense now i know the underlying convention!

**Pull request merged**
